repository_type: pipeline

nf_core_version: 3.4.1

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nf-sentieon-seq_logo_light.png
    - docs/images/nf-core-nf-sentieon-seq_logo_light.png
    - docs/images/nf-core-nf-sentieon-seq_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nf-sentieon-seq_logo_light.png
    - docs/images/nf-core-nf-sentieon-seq_logo_light.png
    - docs/images/nf-core-nf-sentieon-seq_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: sanogenetics
  name: nf-sentieon-seq
  description: Sano Genetics' Variant Calling Pipeline for SNVs and CNVs
  author: Jonathan Talbot-Martin
  version: 1.0.0dev
  force: true
  outdir: /home/ubuntu/persistent/GxG_data/nf-sentieon-sanoseq
  skip_features:
    - adaptivecard
  is_nfcore: false
